#! /bin/sh

#---------------------------------------------------------------------
#                            check-for-tag                            
# 
# Given a tag (--tag), determine if the tag exists or not.
#---------------------------------------------------------------------

#---------------------------------------------------------------------
#                           chicken and egg                           
#---------------------------------------------------------------------

test -f "${FW_ROOT}/share/fw/sh/fw-find.sh" && fws="${FW_ROOT}/share/fw/sh/fw-find.sh"
test -f "fw/sh/fw-find.sh" && fws="fw/sh/fw-find.sh"
test -f "fw.local/sh/fw-find.sh" && fws="fw.local/sh/fw-find.sh"
test ! -z "$fws" || {
  echo "revision/git/check-for-tag: fatal: can't locate fw-find.sh" 1>&2
  exit 1
}

. "$fws"

#---------------------------------------------------------------------
#                              routines                               
#---------------------------------------------------------------------

fw_source "revision/git/check-for-tag" "sh/fatal.sh"
fw_source "revision/git/check-for-tag" "sh/parse-args.sh"
fw_source "revision/git/check-for-tag" "sh/validate-args.sh"

#---------------------------------------------------------------------
#                                main                                 
#---------------------------------------------------------------------

parse_args "revision/git/check-for-tag" "$@"

validate_args "revision/git/check-for-tag" "tag" ""

eval `fw-exec "template/$template/load-config"`

prog="`which git 2>/dev/null`"

test -z "$prog" && {
  echo "revision/git/check-for-tag: fatal: git not installed" 1>&2
  exit 1
}

if TAG_REV=`git rev-list -n 1 "$tag" -- 2>/dev/null`; then
  HEAD_REV=`git rev-list -n 1 HEAD`
  if test "$TAG_REV" != "$HEAD_REV"; then
    echo "$0: incompatible tag $tag already exists" 1>&2
    exit 1
  fi
fi
exit 0
