#! /usr/bin/perl

use File::Basename;

BEGIN {
  unshift @INC, dirname ($0);
};

use FwRpmPackage;
use strict;

#---------------------------------------------------------------------
#                                main                                 
#---------------------------------------------------------------------

my $usage = "package/rpm/check-for-packages: fatal: usage: $0 --arch arch --depends depends --release release --getdeps getdeps\n";

$ARGV[0] eq "--arch" or die $usage;
my $arch = $ARGV[1] or die $usage;
$ARGV[2] eq "--depends" or die $usage;
my $depends = $ARGV[3] or exit 0;       # no dependencies -> automatic win
$ARGV[4] eq "--release" or die $usage;
my $release = $ARGV[5] or die $usage;
$ARGV[6] eq "--getdeps" or die $usage;
my $getdeps= $ARGV[7] or die $usage;

my @packages;
# if getdeps is specified, attempt to use yum to install all the missing
# dependencies.
if ($getdeps eq "yes") {
  my $maxtries = 10;
  my $num_missing = 1000000;
  my @missing = ();
  my @missing_specs = ();
  if ($num_missing > 0) {
    my ($state, undef) = get_state ();
    # we ignore release in the case we are fetching dependencies, otherwise
    # things stop
    my $alldeps = parse_depends ($state, $arch, $depends, "no");
    @packages = @{$alldeps->{"packages"}};
    @missing = @{$alldeps->{"missing"}};
    @missing_specs = @{$alldeps->{"missing_specs"}};
    $num_missing = scalar @missing;
    my %upper_bounded_packages = ();
    my @packages_to_install;
    # go through all missing packages, find out the upper bounded packages
    foreach my $miss (@missing)
    {
      my@array = split /\s+/, $miss;
      if (scalar @array == 3 and ($array[1] eq "<" or $array[1] eq "<=" ))
      {
        $upper_bounded_packages{$array[0]} = 1;
      }
    }

    # go through all missing packages, find out the packages should be put into install command 
    foreach my $miss (@missing)
    {
      my @array = split /\s+/, $miss;
      my $num = scalar @array;
      if ($num == 3) {
        # if the package is upper bounded, do not put it into yum install command
        if (($array[1] eq ">" or $array[1] eq ">=" or $array[1] eq "=") and not defined $upper_bounded_packages{$array[0]}) {
          push @packages_to_install, "\"$miss\"";
        } elsif ($array[1] eq "<" or $array[1] eq "<=") {
          push @packages_to_install, "\"$miss\"";
        } else {
          warn "This dependency is ignored while installing: $miss\n";
        }
      } elsif ($num == 1) {
        push @packages_to_install, "$miss";
      } else {
        warn "This dependency is ignored while installing: $miss\n";
      }
    }

    if (scalar @packages_to_install > 0) {
      my $cmd = "sudo yum install -y @packages_to_install";
      warn "ATTEMPTING TO INSTALL DEPS\n\t".join ("\n\t",@packages_to_install)."\n";
      warn "$cmd\n";
      my $results = `$cmd`;
      my $return_code = $? >> 8;
      warn "$results\n";
    }
  }

  if ($num_missing > 0) {
    my ($state, undef) = get_state ();
    # we ignore release in the case we are fetching dependencies, otherwise
    # things stop
    my $alldeps = parse_depends ($state, $arch, $depends, "no");
    @packages = @{$alldeps->{"packages"}};
    @missing = @{$alldeps->{"missing"}};
    @missing_specs = @{$alldeps->{"missing_specs"}};
    $num_missing = scalar @missing;
  }
  if ($num_missing > 0) {
    die "UNABLE to install build deps still missing\n\t"
        .join ("\n\t",@missing_specs)."\n";
  }
} else {
  my ($state, undef) = get_state ();
  my $alldeps = parse_depends ($state, $arch, $depends, $release);
  @packages = @{$alldeps->{"packages"}};
}

print join "\n", @packages;
print "\n";
